CREATE DATABASE IF NOT EXISTS `chayma` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `chayma`;

CREATE TABLE IF NOT EXISTS `jour` (
  `TDJ` TEXT NULL,
  `S` DECIMAL(10,2) NULL,
  `m` DECIMAL(10,2) NULL,
  `T` DECIMAL(10,2) NULL,
  `SDC` DECIMAL(10,2) NULL,
  `date` DATE NULL,
  `SLT` VARCHAR(255) NULL,
  `autre` TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
